[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
version_files = [
    "pyproject.toml:version",
    "src/rfd/__init__.py:__version__"
]
tag_format = "v$version"
update_changelog_on_bump = true
major_version_zero = true
annotated_tag = true

[tool.commitizen.customize]
bump_pattern = "^(break|feat|fix|perf|refactor)"
bump_map = {"break" = "MAJOR", "feat" = "MINOR", "fix" = "PATCH", "perf" = "PATCH", "refactor" = "PATCH"}