name: Validate Workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Validate GitHub Actions workflows
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
        continue-on-error: true
      
      - name: Test basic package structure
        run: |
          echo "Testing package structure..."
          ls -la src/rfd/
          echo "Testing pyproject.toml validity..."
          python -c "import tomllib; tomllib.load(open('pyproject.toml', 'rb'))"
          echo "✅ Package structure looks good"